---
    version: '2'
    services:
      zookeeper-1:
        image: zookeeper:3.6.2
        hostname: zookeeper-1
        container_name: zookeeper-1
        ### DIFF M2-M3 START: volumes for keystore and truststore added ##################################################
        volumes:
            - ./security/keystore/zookeeper-1.keystore.jks:/security/zookeeper-1.keystore.jks
            - ./security/truststore/zookeeper-1.truststore.jks:/security/zookeeper-1.truststore.jks
        ### DIFF M2-M3 END ################################################################################################
        environment:
          ZOO_MY_ID: 1
          ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
          ### DIFF M2-M3 START: extra zookeeper configs for mTLS added ###################################################
          ZOO_CFG_EXTRA: "sslQuorum=true
                          portUnification=false
                          serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory

                          ssl.quorum.hostnameVerification=false
                          ssl.quorum.keyStore.location=/security/zookeeper-1.keystore.jks
                          ssl.quorum.keyStore.password=password
                          ssl.quorum.trustStore.location=/security/zookeeper-1.truststore.jks
                          ssl.quorum.trustStore.password=password

                          secureClientPort=2281
                          ssl.hostnameVerification=false
                          ssl.keyStore.location=/security/zookeeper-1.keystore.jks
                          ssl.keyStore.password=password
                          ssl.trustStore.location=/security/zookeeper-1.truststore.jks
                          ssl.trustStore.password=password"
          ### DIFF M2-M3 END ###########################################################################################

      zookeeper-2:
        image: zookeeper:3.6.2
        hostname: zookeeper-2
        container_name: zookeeper-2
        ### DIFF M2-M3 START: volumes for keystore and truststore added ##################################################
        volumes:
            - ./security/keystore/zookeeper-2.keystore.jks:/security/zookeeper-2.keystore.jks
            - ./security/truststore/zookeeper-2.truststore.jks:/security/zookeeper-2.truststore.jks
        ### DIFF M2-M3 END #############################################################################################
        environment:
          ZOO_MY_ID: 2
          ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
          ### DIFF M2-M3 START: extra zookeeper configs for mTLS added ###################################################
          ZOO_CFG_EXTRA: "sslQuorum=true
                          portUnification=false
                          serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory

                          ssl.quorum.hostnameVerification=false
                          ssl.quorum.keyStore.location=/security/zookeeper-2.keystore.jks
                          ssl.quorum.keyStore.password=password
                          ssl.quorum.trustStore.location=/security/zookeeper-2.truststore.jks
                          ssl.quorum.trustStore.password=password

                          secureClientPort=2281
                          ssl.hostnameVerification=false
                          ssl.keyStore.location=/security/zookeeper-2.keystore.jks
                          ssl.keyStore.password=password
                          ssl.trustStore.location=/security/zookeeper-2.truststore.jks
                          ssl.trustStore.password=password"
          ### DIFF M2-M3 END ###########################################################################################

      zookeeper-3:
        image: zookeeper:3.6.2
        hostname: zookeeper-3
        container_name: zookeeper-3
        ### DIFF M2-M3 START: volumes for keystore and truststore added ###############################################
        volumes:
            - ./security/keystore/zookeeper-3.keystore.jks:/security/zookeeper-3.keystore.jks
            - ./security/truststore/zookeeper-3.truststore.jks:/security/zookeeper-3.truststore.jks
        ### DIFF M2-M3 END #############################################################################################
        environment:
          ZOO_MY_ID: 3
          ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
          ### DIFF M2-M3 START: extra zookeeper configs for mTLS added ###################################################
          ZOO_CFG_EXTRA: "sslQuorum=true
                          portUnification=false
                          serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory

                          ssl.quorum.hostnameVerification=false
                          ssl.quorum.keyStore.location=/security/zookeeper-3.keystore.jks
                          ssl.quorum.keyStore.password=password
                          ssl.quorum.trustStore.location=/security/zookeeper-3.truststore.jks
                          ssl.quorum.trustStore.password=password

                          secureClientPort=2281
                          ssl.hostnameVerification=false
                          ssl.keyStore.location=/security/zookeeper-3.keystore.jks
                          ssl.keyStore.password=password
                          ssl.trustStore.location=/security/zookeeper-3.truststore.jks
                          ssl.trustStore.password=password"
          ### DIFF M2-M3 END ###########################################################################################

      broker-1:
        image: bsucaciu/kafka:2.6.0
        hostname: broker-1
        container_name: broker-1
        depends_on:
          - zookeeper-1
          - zookeeper-2
          - zookeeper-3
        ports:
          - "9091:9091"
          - "9191:9191"
        ### DIFF M2-M3 START: volumes for keystore and truststore added ################################################
        volumes:
            - ./security/keystore/broker-1.keystore.jks:/kafka/security/broker-1.keystore.jks
            - ./security/truststore/broker-1.truststore.jks:/kafka/security/broker-1.truststore.jks
        ### DIFF M2-M3 END #############################################################################################
        environment:
          KAFKA_BROKER_ID: 1
          ### DIFF M2-M3 START: zookeeper port is now 2281 instead of 2181 (corr ZOO_CFG_EXTRA: secureClientPort=2281) ##
          KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2281,zookeeper-2:2281,zookeeper-3:2281
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SSL,EXTERNAL:PLAINTEXT, EXTERNAL_SSL:SSL
          KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-1:29091,EXTERNAL://localhost:9091,EXTERNAL_SSL://localhost:9191
          KAFKA_LISTENERS: INTERNAL://0.0.0.0:29091,EXTERNAL://0.0.0.0:9091,EXTERNAL_SSL://0.0.0.0:9191
          KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
          KAFKA_DEFAULT_REPLICATION_FACTOR: 3
          KAFKA_MIN_INSYNC_REPLICAS: 2
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
          ### DIFF M2-M3 START: extra kafka configs for zookeeper mTLS added #############################################
          KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: "true"
          KAFKA_ZOOKEEPER_CLIENT_CNXN_SOCKET: org.apache.zookeeper.ClientCnxnSocketNetty
          KAFKA_ZOOKEEPER_SSL_KEYSTORE_LOCATION: /kafka/security/broker-1.keystore.jks
          KAFKA_ZOOKEEPER_SSL_KEYSTORE_PASSWORD: password
          KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /kafka/security/broker-1.truststore.jks
          KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: password
          ### DIFF M2-M3 END ###########################################################################################
          KAFKA_SSL_CLIENT_AUTH: none
          KAFKA_SSL_KEYSTORE_LOCATION: /kafka/security/broker-1.keystore.jks
          KAFKA_SSL_KEYSTORE_PASSWORD: password
          KAFKA_SSL_KEY_PASSWORD: password
          KAFKA_SSL_TRUSTSTORE_LOCATION: /kafka/security/broker-1.truststore.jks
          KAFKA_SSL_TRUSTSTORE_PASSWORD: password
          KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL

      broker-2:
        image: bsucaciu/kafka:2.6.0
        hostname: broker-2
        container_name: broker-2
        depends_on:
          - zookeeper-1
          - zookeeper-2
          - zookeeper-3
        ports:
          - "9092:9092"
          - "9192:9192"
        ### DIFF M2-M3 START: volumes for keystore and truststore added ##################################################
        volumes:
            - ./security/keystore/broker-2.keystore.jks:/kafka/security/broker-2.keystore.jks
            - ./security/truststore/broker-2.truststore.jks:/kafka/security/broker-2.truststore.jks
        ### DIFF M2-M3 END #############################################################################################
        environment:
          KAFKA_BROKER_ID: 2
          ### DIFF M2-M3 START: zookeeper port is now 2281 instead of 2181 (corr ZOO_CFG_EXTRA: secureClientPort=2281) ##
          KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2281,zookeeper-2:2281,zookeeper-3:2281
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SSL,EXTERNAL:PLAINTEXT, EXTERNAL_SSL:SSL
          KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-2:29092,EXTERNAL://localhost:9092,EXTERNAL_SSL://localhost:9192
          KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,EXTERNAL_SSL://0.0.0.0:9192
          KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
          KAFKA_DEFAULT_REPLICATION_FACTOR: 3
          KAFKA_MIN_INSYNC_REPLICAS: 2
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
          ### DIFF M2-M3 START: extra kafka configs for zookeeper mTLS added #############################################
          KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: "true"
          KAFKA_ZOOKEEPER_CLIENT_CNXN_SOCKET: org.apache.zookeeper.ClientCnxnSocketNetty
          KAFKA_ZOOKEEPER_SSL_KEYSTORE_LOCATION: /kafka/security/broker-2.keystore.jks
          KAFKA_ZOOKEEPER_SSL_KEYSTORE_PASSWORD: password
          KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /kafka/security/broker-2.truststore.jks
          KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: password
          ### DIFF M2-M3 END ###########################################################################################
          KAFKA_SSL_CLIENT_AUTH: none
          KAFKA_SSL_KEYSTORE_LOCATION: /kafka/security/broker-2.keystore.jks
          KAFKA_SSL_KEYSTORE_PASSWORD: password
          KAFKA_SSL_KEY_PASSWORD: password
          KAFKA_SSL_TRUSTSTORE_LOCATION: /kafka/security/broker-2.truststore.jks
          KAFKA_SSL_TRUSTSTORE_PASSWORD: password
          KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL

      broker-3:
        image: bsucaciu/kafka:2.6.0
        hostname: broker-3
        container_name: broker-3
        depends_on:
          - zookeeper-1
          - zookeeper-2
          - zookeeper-3
        ports:
          - "9093:9093"
          - "9193:9193"
        ### DIFF M2-M3 START: volumes for keystore and truststore added ##################################################
        volumes:
            - ./security/keystore/broker-3.keystore.jks:/kafka/security/broker-3.keystore.jks
            - ./security/truststore/broker-3.truststore.jks:/kafka/security/broker-3.truststore.jks
        ### DIFF M2-M3 END #############################################################################################
        environment:
          KAFKA_BROKER_ID: 3
          ### DIFF M2-M3 START: zookeeper port is now 2281 instead of 2181 (corr ZOO_CFG_EXTRA: secureClientPort=2281) ##
          KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2281,zookeeper-2:2281,zookeeper-3:2281
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SSL,EXTERNAL:PLAINTEXT, EXTERNAL_SSL:SSL
          KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-3:29093,EXTERNAL://localhost:9093,EXTERNAL_SSL://localhost:9193
          KAFKA_LISTENERS: INTERNAL://0.0.0.0:29093,EXTERNAL://0.0.0.0:9093,EXTERNAL_SSL://0.0.0.0:9193
          KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
          KAFKA_DEFAULT_REPLICATION_FACTOR: 3
          KAFKA_MIN_INSYNC_REPLICAS: 2
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
          ### DIFF M2-M3 START: extra kafka configs for zookeeper mTLS added #############################################
          KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: "true"
          KAFKA_ZOOKEEPER_CLIENT_CNXN_SOCKET: org.apache.zookeeper.ClientCnxnSocketNetty
          KAFKA_ZOOKEEPER_SSL_KEYSTORE_LOCATION: /kafka/security/broker-3.keystore.jks
          KAFKA_ZOOKEEPER_SSL_KEYSTORE_PASSWORD: password
          KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /kafka/security/broker-3.truststore.jks
          KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: password
          ### DIFF M2-M3 END ###########################################################################################
          KAFKA_SSL_CLIENT_AUTH: none
          KAFKA_SSL_KEYSTORE_LOCATION: /kafka/security/broker-3.keystore.jks
          KAFKA_SSL_KEYSTORE_PASSWORD: password
          KAFKA_SSL_KEY_PASSWORD: password
          KAFKA_SSL_TRUSTSTORE_LOCATION: /kafka/security/broker-3.truststore.jks
          KAFKA_SSL_TRUSTSTORE_PASSWORD: password
          KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
