---
    version: '2'
    services:
      zookeeper-1:
        image: zookeeper:3.6.2
        hostname: zookeeper-1
        container_name: zookeeper-1
        volumes:
            - ./security/keystore/zookeeper-1.keystore.jks:/security/zookeeper-1.keystore.jks
            - ./security/truststore/zookeeper-1.truststore.jks:/security/zookeeper-1.truststore.jks
        environment:
          ZOO_MY_ID: 1
          ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
          ZOO_CFG_EXTRA: "sslQuorum=true
                          portUnification=false
                          serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory

                          ssl.quorum.hostnameVerification=false
                          ssl.quorum.keyStore.location=/security/zookeeper-1.keystore.jks
                          ssl.quorum.keyStore.password=password
                          ssl.quorum.trustStore.location=/security/zookeeper-1.truststore.jks
                          ssl.quorum.trustStore.password=password

                          secureClientPort=2281
                          ssl.hostnameVerification=false
                          ssl.keyStore.location=/security/zookeeper-1.keystore.jks
                          ssl.keyStore.password=password
                          ssl.trustStore.location=/security/zookeeper-1.truststore.jks
                          ssl.trustStore.password=password"

      zookeeper-2:
        image: zookeeper:3.6.2
        hostname: zookeeper-2
        container_name: zookeeper-2
        volumes:
            - ./security/keystore/zookeeper-2.keystore.jks:/security/zookeeper-2.keystore.jks
            - ./security/truststore/zookeeper-2.truststore.jks:/security/zookeeper-2.truststore.jks
        environment:
          ZOO_MY_ID: 2
          ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
          ZOO_CFG_EXTRA: "sslQuorum=true
                          portUnification=false
                          serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory

                          ssl.quorum.hostnameVerification=false
                          ssl.quorum.keyStore.location=/security/zookeeper-2.keystore.jks
                          ssl.quorum.keyStore.password=password
                          ssl.quorum.trustStore.location=/security/zookeeper-2.truststore.jks
                          ssl.quorum.trustStore.password=password

                          secureClientPort=2281
                          ssl.hostnameVerification=false
                          ssl.keyStore.location=/security/zookeeper-2.keystore.jks
                          ssl.keyStore.password=password
                          ssl.trustStore.location=/security/zookeeper-2.truststore.jks
                          ssl.trustStore.password=password"

      zookeeper-3:
        image: zookeeper:3.6.2
        hostname: zookeeper-3
        container_name: zookeeper-3
        volumes:
            - ./security/keystore/zookeeper-3.keystore.jks:/security/zookeeper-3.keystore.jks
            - ./security/truststore/zookeeper-3.truststore.jks:/security/zookeeper-3.truststore.jks
        environment:
          ZOO_MY_ID: 3
          ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
          ZOO_CFG_EXTRA: "sslQuorum=true
                          portUnification=false
                          serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory

                          ssl.quorum.hostnameVerification=false
                          ssl.quorum.keyStore.location=/security/zookeeper-3.keystore.jks
                          ssl.quorum.keyStore.password=password
                          ssl.quorum.trustStore.location=/security/zookeeper-3.truststore.jks
                          ssl.quorum.trustStore.password=password

                          secureClientPort=2281
                          ssl.hostnameVerification=false
                          ssl.keyStore.location=/security/zookeeper-3.keystore.jks
                          ssl.keyStore.password=password
                          ssl.trustStore.location=/security/zookeeper-3.truststore.jks
                          ssl.trustStore.password=password"

      broker-1:
        image: bsucaciu/kafka:2.6.0
        hostname: broker-1
        container_name: broker-1
        domainname: ps-securing-kafka_default
        depends_on:
          - zookeeper-1
          - zookeeper-2
          - zookeeper-3
        ports:
          - "9191:9191"
          - "9291:9291"
        volumes:
            - ./security/keystore/broker-1.keystore.jks:/kafka/security/broker-1.keystore.jks
            - ./security/truststore/broker-1.truststore.jks:/kafka/security/broker-1.truststore.jks
            - ./security/authentication/sasl_gssapi/broker1_jaas_gssapi.conf:/kafka/security/kafka_jaas.conf
            - ./security/authentication/sasl_gssapi/keytabs/broker1.keytab:/kafka/security/keytabs/kafka_server.keytab
            - ./security/authentication/sasl_gssapi/krb5.conf:/kafka/security/krb5.conf
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2281,zookeeper-2:2281,zookeeper-3:2281
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SSL:SSL,SASL_SSL:SASL_SSL
          KAFKA_ADVERTISED_LISTENERS: SSL://broker-1:9191,SASL_SSL://broker-1:9291
          KAFKA_LISTENERS: SSL://broker-1:9191,SASL_SSL://broker-1:9291
          KAFKA_DEFAULT_REPLICATION_FACTOR: 3
          KAFKA_MIN_INSYNC_REPLICAS: 2
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
          KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: "true"
          KAFKA_ZOOKEEPER_CLIENT_CNXN_SOCKET: org.apache.zookeeper.ClientCnxnSocketNetty
          KAFKA_ZOOKEEPER_SSL_KEYSTORE_LOCATION: /kafka/security/broker-1.keystore.jks
          KAFKA_ZOOKEEPER_SSL_KEYSTORE_PASSWORD: password
          KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /kafka/security/broker-1.truststore.jks
          KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: password
          KAFKA_SSL_CLIENT_AUTH: required # check: this works, but example changed back to none without explaining in the video
          KAFKA_SSL_KEYSTORE_LOCATION: /kafka/security/broker-1.keystore.jks
          KAFKA_SSL_KEYSTORE_PASSWORD: password
          KAFKA_SSL_KEY_PASSWORD: password
          KAFKA_SSL_TRUSTSTORE_LOCATION: /kafka/security/broker-1.truststore.jks
          KAFKA_SSL_TRUSTSTORE_PASSWORD: password

          KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_SSL
          KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: GSSAPI
          KAFKA_SASL_ENABLED_MECHANISMS: GSSAPI
          KAFKA_SASL_KERBEROS_SERVICE_NAME: kafka

          KAFKA_OPTS: "-Djava.security.auth.login.config=/kafka/security/kafka_jaas.conf
                       -Djava.security.krb5.conf=/kafka/security/krb5.conf"


      broker-2:
        image: bsucaciu/kafka:2.6.0
        hostname: broker-2
        container_name: broker-2
        domainname: ps-securing-kafka_default
        depends_on:
          - zookeeper-1
          - zookeeper-2
          - zookeeper-3
        ports:
          - "9192:9192"
          - "9292:9292"
        volumes:
            - ./security/keystore/broker-2.keystore.jks:/kafka/security/broker-2.keystore.jks
            - ./security/truststore/broker-2.truststore.jks:/kafka/security/broker-2.truststore.jks
            - ./security/authentication/sasl_gssapi/broker2_jaas_gssapi.conf:/kafka/security/kafka_jaas.conf
            - ./security/authentication/sasl_gssapi/keytabs/broker2.keytab:/kafka/security/keytabs/kafka_server.keytab
            - ./security/authentication/sasl_gssapi/krb5.conf:/kafka/security/krb5.conf
        environment:
          KAFKA_BROKER_ID: 2
          KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2281,zookeeper-2:2281,zookeeper-3:2281
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SSL:SSL,SASL_SSL:SASL_SSL
          KAFKA_ADVERTISED_LISTENERS: SSL://broker-2:9192,SASL_SSL://broker-2:9292
          KAFKA_LISTENERS: SSL://broker-2:9192,SASL_SSL://broker-2:9292
          KAFKA_DEFAULT_REPLICATION_FACTOR: 3
          KAFKA_MIN_INSYNC_REPLICAS: 2
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
          KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: "true"
          KAFKA_ZOOKEEPER_CLIENT_CNXN_SOCKET: org.apache.zookeeper.ClientCnxnSocketNetty
          KAFKA_ZOOKEEPER_SSL_KEYSTORE_LOCATION: /kafka/security/broker-2.keystore.jks 
          KAFKA_ZOOKEEPER_SSL_KEYSTORE_PASSWORD: password
          KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /kafka/security/broker-2.truststore.jks
          KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: password
          KAFKA_SSL_CLIENT_AUTH: required # check: this works, but example changed back to none without explaining in the video
          KAFKA_SSL_KEYSTORE_LOCATION: /kafka/security/broker-2.keystore.jks
          KAFKA_SSL_KEYSTORE_PASSWORD: password
          KAFKA_SSL_KEY_PASSWORD: password
          KAFKA_SSL_TRUSTSTORE_LOCATION: /kafka/security/broker-2.truststore.jks
          KAFKA_SSL_TRUSTSTORE_PASSWORD: password

          KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_SSL
          KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: GSSAPI
          KAFKA_SASL_ENABLED_MECHANISMS: GSSAPI
          KAFKA_SASL_KERBEROS_SERVICE_NAME: kafka

          KAFKA_OPTS: "-Djava.security.auth.login.config=/kafka/security/kafka_jaas.conf
                       -Djava.security.krb5.conf=/kafka/security/krb5.conf"
    
      broker-3:
        image: bsucaciu/kafka:2.6.0
        hostname: broker-3
        container_name: broker-3
        domainname: ps-securing-kafka_default
        depends_on:
          - zookeeper-1
          - zookeeper-2
          - zookeeper-3
        ports:
          - "9193:9193"
          - "9293:9293"
        volumes:
            - ./security/keystore/broker-3.keystore.jks:/kafka/security/broker-3.keystore.jks
            - ./security/truststore/broker-3.truststore.jks:/kafka/security/broker-3.truststore.jks
            - ./security/authentication/sasl_gssapi/broker3_jaas_gssapi.conf:/kafka/security/kafka_jaas.conf
            - ./security/authentication/sasl_gssapi/keytabs/broker3.keytab:/kafka/security/keytabs/kafka_server.keytab
            - ./security/authentication/sasl_gssapi/krb5.conf:/kafka/security/krb5.conf
        environment:
          KAFKA_BROKER_ID: 3
          KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2281,zookeeper-2:2281,zookeeper-3:2281
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SSL:SSL,SASL_SSL:SASL_SSL
          KAFKA_ADVERTISED_LISTENERS: SSL://broker-3:9193,SASL_SSL://broker-3:9293
          KAFKA_LISTENERS: SSL://broker-3:9193,SASL_SSL://broker-3:9293
          KAFKA_DEFAULT_REPLICATION_FACTOR: 3
          KAFKA_MIN_INSYNC_REPLICAS: 2
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
          KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: "true"
          KAFKA_ZOOKEEPER_CLIENT_CNXN_SOCKET: org.apache.zookeeper.ClientCnxnSocketNetty
          KAFKA_ZOOKEEPER_SSL_KEYSTORE_LOCATION: /kafka/security/broker-3.keystore.jks
          KAFKA_ZOOKEEPER_SSL_KEYSTORE_PASSWORD: password
          KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /kafka/security/broker-3.truststore.jks
          KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: password
          KAFKA_SSL_CLIENT_AUTH: required # check: this works, but example changed back to none without explaining in the video
          KAFKA_SSL_KEYSTORE_LOCATION: /kafka/security/broker-3.keystore.jks
          KAFKA_SSL_KEYSTORE_PASSWORD: password
          KAFKA_SSL_KEY_PASSWORD: password
          KAFKA_SSL_TRUSTSTORE_LOCATION: /kafka/security/broker-3.truststore.jks
          KAFKA_SSL_TRUSTSTORE_PASSWORD: password

          KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_SSL
          KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: GSSAPI
          KAFKA_SASL_ENABLED_MECHANISMS: GSSAPI
          KAFKA_SASL_KERBEROS_SERVICE_NAME: kafka

          KAFKA_OPTS: "-Djava.security.auth.login.config=/kafka/security/kafka_jaas.conf
                       -Djava.security.krb5.conf=/kafka/security/krb5.conf"


      kerberos:
        image: bsucaciu/kerberos:krb5
        hostname: kerberos
        container_name: kerberos
        ports:
          - 88:88
          - 464:464
          - 749:749
        volumes:
            #- ./security/kerberos/:/etc/security/
            - ./security/authentication/sasl_gssapi/keytabs/:/etc/security/keytabs/
        environment:
          KRB5_REALM: PLURALSIGHT.COM
          KRB5_KDC: kerberos
          KRB5_PASS: password

      consumer:
        image: bsucaciu/kerberos-consumer:1.0.0
        hostname: consumer
        container_name: consumer
        domainname: ps-securing-kafka_default
        volumes:
            - ./security/authentication/sasl_gssapi/keytabs/consumer.keytab:/security/consumer.keytab

      producer:
        image: bsucaciu/kerberos-producer:1.0.0
        hostname: producer
        container_name: producer
        domainname: ps-securing-kafka_default
        volumes:
            - ./security/authentication/sasl_gssapi/keytabs/producer.keytab:/security/producer.keytab
